WVER_STATIONS = {
    "stb_heimbach_uw": {
        "name": "Stb. Heimbach UW",
        "page_url": "https://wver.de/karten_messwerte/Messdatenportal/Stb.%20Heimbach%20UW.html",
        "primary_signal": "wasserstand",
        "signals": {
            "wasserstand": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Heimbach%20UWWasserstandBasis.P.json",
            "grenzwert_1": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Heimbach%20UWWasserstandGW1_Homepage_ausgerollt.json",
            "grenzwert_2": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Heimbach%20UWWasserstandGW2_Homepage_ausgerollt.json",
            "abfluss": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Heimbach%20UWAbflussBasis.P.json",
        },
    },
    "stb_obermaubach_uw": {
        "name": "Stb. Obermaubach UW",
        "page_url": "https://wver.de/karten_messwerte/Messdatenportal/Stb.%20Obermaubach%20UW.html",
        "primary_signal": "wasserstand",
        "signals": {
            "wasserstand": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Obermaubach%20UWWasserstandBasis.P.json",
            "grenzwert_1": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Obermaubach%20UWWasserstandGW1_Homepage_ausgerollt.json",
            "grenzwert_2": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Obermaubach%20UWWasserstandGW2_Homepage_ausgerollt.json",
            "abfluss": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Stb.%20Obermaubach%20UWAbflussBasis.P.json",
        },
    },
    "rur_monschau_lanuk": {
        "name": "Rur Monschau LANUK",
        "page_url": "https://wver.de/karten_messwerte/Messdatenportal/Rur%20Monschau%20LANUK.html",
        "primary_signal": "wasserstand",
        "signals": {
            "wasserstand": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20Monschau%20LANUKWasserstandImport_Internet.P.json",
            "informationswert_1": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20Monschau%20LANUKWasserstandInformationswert1_ausgerollt.json",
            "informationswert_2": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20Monschau%20LANUKWasserstandInformationswert2_ausgerollt.json",
            "informationswert_3": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20Monschau%20LANUKWasserstandInformationswert3_ausgerollt.json",
        },
    },
    "rur_dedenborn": {
        "name": "Rur Dedenborn",
        "page_url": "https://wver.de/karten_messwerte/Messdatenportal/Rur%20Dedenborn.html",
        "primary_signal": "wasserstand",
        "signals": {
            "wasserstand": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20DedenbornWasserstandBasis.P.json",
            "grenzwert_1": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20DedenbornWasserstandGW1_Homepage_ausgerollt.json",
            "grenzwert_2": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20DedenbornWasserstandGW2_Homepage_ausgerollt.json",
            "abfluss": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rur%20DedenbornAbflussBasis.P.json",
        },
    },
    "rurtalsperre_schwammenauel": {
        "name": "Rurtalsperre Schwammenauel",
        "page_url": "https://wver.de/karten_messwerte/Messdatenportal/Rurtalsperre%20Schwammenauel.html",
        "primary_signal": "wasserstand_hauptsee",
        "signals": {
            "abgabe_hauptsee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20AbflussAbflussTag.Mittel.json",
            "zufluss_obersee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Obersee%20ZuflussAbflussQ_Summe_Tag.Mittel.json",
            "niederschlag": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Schwammenauel%20KlimaNiederschlagTag.Summe.json",
            "wasserstand_hauptsee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20OWWasserspiegelTag.Mittel.json",
            "wasserstand_hauptsee_seit_wwj2001": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20OWWasserspiegelTag.Mittel.seitWWJ2001.json",
            "stauziel_hauptsee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20BetriebsplanWasserspiegelDay.Cmd.Stauziel.json",
            "vollstau_hauptsee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20BetriebsplanWasserspiegelDay.Cmd.Vollstau.json",
            "hoechstes_stauziel_hauptsee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20BetriebsplanWasserspiegelDay.Cmd.h%C3%B6chstes.Stauziel.json",
            "stauziel_hauptsee_min": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Hauptsee%20BetriebsplanWasserspiegelStauziel.HS_min.json",
            "wasserstand_obersee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Obersee%20OWWasserspiegelTag.Mittel.json",
            "stauziel_obersee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Obersee%20BetriebsplanWasserspiegelDay.Cmd.Stauziel.json",
            "vollstau_obersee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Obersee%20BetriebsplanWasserspiegelDay.Cmd.Vollstau.json",
            "hoechstes_stauziel_obersee": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Rurtalsperre%20Obersee%20BetriebsplanWasserspiegelDay.Cmd.h%C3%B6chstes.Stauziel.json",
        },
    },
    "urfttalsperre": {
        "name": "Urfttalsperre",
        "page_url": "https://wver.de/karten_messwerte/Messdatenportal/Urfttalsperre.html",
        "primary_signal": "wasserstand",
        "signals": {
            "abgabe": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20AbflussAbflussQ_gesamt_Tag.Mittel.json",
            "zufluss": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20ZuflussAbflussTag.Mittel.json",
            "niederschlag": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20KlimaNiederschlagTag.Summe.json",
            "wasserstand": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20OWWasserspiegelTag.Mittel.json",
            "wasserstand_seit_wwj2001": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20OWWasserspiegelTag.Mittel.seitWWJ2001.json",
            "stauziel": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20BetriebsplanWasserspiegelDay.Cmd.Stauziel.json",
            "vollstau": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20BetriebsplanWasserspiegelDay.Cmd.Vollstau.json",
            "hoechstes_stauziel": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20BetriebsplanWasserspiegelDay.Cmd.h%C3%B6chstes.Stauziel.json",
            "stauziel_min": "https://wver.de/karten_messwerte/Messdatenportal/Messdaten/Urfttalsperre%20BetriebsplanWasserspiegelStauziel.HS_min.json",
        },
    },
}